### ISSUE TITLE
ApartmentRatings added new property in reviews

### ISSUE THREAD

**Issue by lsajja3** [gregory/apartment_ratings#1]
Hashie::CoercionError: Cannot coerce property "reviews" from Array to #Set:0x007fdc22bba6d8: The property 'recommend' is not defined for ApartmentRatings::Review.

@gregory - i cloned the repo and added the property, can't push the dev branch as i dont have permission. can you please give my username permission to push to this repo?

**Comment by gregory** [comment]
Hey @lsajja3 feel free to open PR against this repo to contribute to open source ;) I'll grant you some access for you to work on it! thanks :)

**Comment by lsajja3** [comment]
Thanks greg, once you merge my branch, what should I do? Should I have to do bundle update/gem update on production server to use the new changes?

**Comment by gregory** [comment]
@lsajja3 i cut a new 1.1.1 release and pushed to rubygems. you can just do a `bundle update apartment_ratings` and make sure you use the 1.1.1 in your gemfile.lock. then re deploy ;) 

ping me if you have any question!
